### ISSUE TITLE
User can create a project 

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/thoughtBoard.io#2]
## Goal: 
 - User can create a new project to associate future notes with. The project gets saved to DB

## ✅ Task List
- [x] Create header component
- [x] create drop-down menu from material UI
- [x] Adjust font size on proj selector component
- [x] adjust total size of proj selector
- [x] Create sample project
- [x] Add icon to add new project
- [x] Change new proj button to button element
- [x] create new project form
- [x] add proj form to header section,
- [x] add state to header section to conditionally display form or not
- [x] create on click function that displays from for new project details
- [x] set new project as current project
- [x] set hash route to projects ***
- [x] create ID for new project
- [x] save to DB
- [x] update Hash Route using anchor tag
- [x] Create a state that tracks which project has been selected 
- [x] create fields for project name
- [x] Define a user
- [x] Check local storage for jwt
----
- [x] if no jwt, send api request to create a user
- [x] create user in db
- [x] create jwt from user data
- [x] return jwt to front end
----
- [x] if yes,
- [x] use token to retrieve user data/projects 
----
- [x] Create state in thoughtBoard component to keep track of current porject
- [x] update state on new projec creation
- [x] update state on project selection
- [x] Get uiser's projects from DB
- [x] render projects from database into selector 
- [x] add db return for new project to project state and render in selector 
----
- [x] create form to create user
- [x] create db schema 
- [x] save project to db
- [x] Clean up code: 
     - [x] update styles
     - [x] projectSelector.jsx -> MenuProps 
     - [x] Move styles to their own files
     - [x] organize file structure
     - [x] modulize code
     - [x] make sure code is uniform (ex: e v. event) 
     - [x] Destructure imports
     - [x] Fix router bug (manual urls) 
     - [x] put projects into react context
     - [x] remove comments
