### ISSUE TITLE
User can create a note

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/thoughtBoard.io#3]
##Design

## Goal: 
 - Create a note item within the sidebar component and create a blank artboard.

## ✅ Task List
- [x] create side bar ( use proper material ui practices )
- [x] set width to 1/4 the size of screen on desktop
- [x] set bg color to dark grey
- [x] Add new note button
- [x] on click: generate new note -> append new note to side bar ul container
- [x] generate a new note item
- [x] give note a generic title
- [x] give note a date
- [x] assign note to project
- [x] create empty data value
- [x] add highligh on selected note
- [x] add state prop to add selected note
- [x] ensure multiple note can be selected 
- [x] test overflow y
- [x] save all new notes to db
---
- [x] create mobile design
- [x] optimize entire site for mobile ( use material ui best practices )
- [x] hide header
- [x] hide sidebar
- [x] add controls to empty space where thoughtBoard will go
---
- [x] add nextNoteId to project data, to keep track of note id's
- [x] try-catch in async functions
